// ─── Types ────────────────────────────────────────────────────────────────────
// ─── Images ───────────────────────────────────────────────────────────────────
export const IMG = {
    hero: 'https://images.unsplash.com/photo-1598629978663-1e59ce59de90?w=1200&h=900&fit=crop&auto=format',
    video: 'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=1200&h=700&fit=crop&auto=format',
    physical: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=500&fit=crop&auto=format',
    emotional: 'https://images.unsplash.com/photo-1524069290683-0457abfe42c3?w=800&h=500&fit=crop&auto=format',
    intellectual: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&h=500&fit=crop&auto=format',
    social: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&h=500&fit=crop&auto=format',
    spiritual: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop&auto=format',
    digital: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=500&fit=crop&auto=format',
    sexual: 'https://images.unsplash.com/photo-1646671357082-c05f07b9b45d?w=800&h=500&fit=crop&auto=format',
};
// ─── Data ─────────────────────────────────────────────────────────────────────
export const dimensions = [
    {
        id: 'physical', num: '01', name: 'Physical', icon: '🏃',
        color: '#DC2626', colorLight: 'rgba(220,38,38,0.08)',
        tagline: 'Your Body, Your Foundation',
        shortDesc: 'How you relate to your body, health, energy, and physical well-being.',
        description: 'The physical self refers to how a person understands and views their physical body, including their appearance, physical abilities, health, and body characteristics. It is how you recognize and understand your body as part of who you are.',
        example: 'It affects how we take care of our bodies, maintain our health, participate in activities, interact with our surroundings, and become aware of our physical needs and limitations.',
        reflectiveQuestion: 'When did you last truly listen to what your body was telling you — and what did it say?',
        image: IMG.physical,
        quote: { text: "Take care of your body. It's the only place you have to live.", author: 'Jim Rohn' },
        lessons: [
            { title: 'Body Awareness', body: 'Your body is constantly communicating through sensation, energy, tension, and hunger. Developing somatic awareness — the skill of listening to your body — is the first step to physical self-knowledge. Many people live almost entirely "in their heads," disconnected from the signals that guide well-being.' },
            { title: 'Movement & Energy', body: 'Physical activity does far more than build fitness. Movement releases endorphins, regulates stress hormones, improves sleep, and sharpens thinking. The most sustainable approach is finding forms of movement that feel joyful rather than obligatory — whether that is walking, dancing, sport, or yoga.' },
            { title: 'Rest & Recovery', body: 'In a culture that celebrates busyness, rest is undervalued. Sleep is when the brain consolidates memory, repairs the body, and regulates emotion. Protecting rest is not laziness — it is an act of intelligence.' },
            { title: 'Nourishment', body: 'How we nourish our bodies directly shapes mental clarity, emotional stability, and energy. The healthiest relationship with food is one of curiosity and care — asking what genuinely makes you feel alive, energized, and well — rather than one of restriction or guilt.' },
        ],
        practices: [
            'Do a 5-minute body scan each morning — notice tension, energy, and sensation without judgment.',
            'Track your energy levels across the day for one week to find your natural rhythm.',
            'Choose one form of joyful movement and practice it three times this week.',
            'Create a consistent sleep routine and protect the hour before bed from screens.',
        ],
    },
    {
        id: 'emotional', num: '02', name: 'Emotional', icon: '💛',
        color: '#D97706', colorLight: 'rgba(217,119,6,0.08)',
        tagline: 'Feeling as a Form of Knowing',
        shortDesc: 'Your feelings, emotional patterns, empathy, and capacity for self-regulation.',
        description: 'The emotional self refers to your ability to recognize, understand, express, and manage your emotions. It includes being aware of what you feel and understanding how your emotions can influence your thoughts and actions.',
        example: 'It affects how we respond to situations, handle stress and challenges, communicate our feelings, build relationships, make decisions, and cope with different experiences.',
        reflectiveQuestion: 'What emotion have you been avoiding lately — and what might it be trying to tell you?',
        image: IMG.emotional,
        quote: { text: 'Emotion is the chief source of all becoming-conscious.', author: 'Carl Jung' },
        lessons: [
            { title: 'Emotional Vocabulary', body: 'Most people use a very limited emotional vocabulary — happy, sad, angry, fine. But emotions are far more nuanced. There is a difference between irritation, frustration, and rage; between melancholy, grief, and despair. Expanding your emotional vocabulary leads to greater self-understanding and clearer communication.' },
            { title: 'Emotions as Information', body: 'Emotions are not problems to be solved — they are signals. Fear signals potential threat. Grief signals loss and love. Anger signals a boundary or value has been crossed. Joy signals alignment with what matters. Learning to "read" emotions rather than suppress them is a core skill of emotional intelligence.' },
            { title: 'Self-Regulation', body: "Regulation does not mean suppression. It means the ability to acknowledge, process, and respond to emotions in ways that serve you. Practical tools include: naming the emotion, pausing before responding, deep breathing, journaling, and grounding techniques." },
            { title: 'Empathy & Connection', body: "Emotional intelligence extends outward into empathy — the capacity to sense and understand what others feel. Empathy is not agreement; it is presence. It is the ability to be with another's experience without trying to fix, minimize, or redirect it." },
        ],
        practices: [
            'Keep a daily emotion log — write what you felt, when, and what triggered it.',
            'Practice naming emotions precisely. Try the "Feelings Wheel" for expanded vocabulary.',
            'When a strong emotion arises, pause and ask: "What is this feeling trying to tell me?"',
            'Practice active listening — reflect back what you hear without offering solutions.',
        ],
    },
    {
        id: 'intellectual', num: '03', name: 'Intellectual', icon: '🧠',
        color: '#7C3AED', colorLight: 'rgba(124,58,237,0.08)',
        tagline: 'The Life of the Mind',
        shortDesc: 'Your thoughts, beliefs, curiosity, reasoning, and how you make meaning.',
        description: 'The intellectual self refers to your ability to think, learn, understand, reason, solve problems, and gain knowledge. It includes how you view your abilities as a learner and thinker.',
        example: 'It is involved whenever we learn something new, make choices, solve problems, analyze situations, form opinions, study, work, or try to understand the world around us.',
        reflectiveQuestion: 'What belief have you held the longest without genuinely questioning it?',
        image: IMG.intellectual,
        quote: { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
        lessons: [
            { title: 'The Architecture of Beliefs', body: 'Your beliefs are the invisible structure of your reality. They shape what you notice, how you interpret events, and what choices you make. Many beliefs were formed in childhood and have never been examined. Intellectual self-knowledge begins with asking: "What do I believe, and why do I believe it?"' },
            { title: 'Critical Thinking', body: 'Critical thinking — the ability to reason clearly, evaluate evidence, and question assumptions — is not just an academic skill. It is a form of self-respect. When you think clearly, you are less susceptible to manipulation and better equipped to pursue what is genuinely true and good.' },
            { title: "Curiosity as Identity", body: "Curiosity is the intellectual self's native state. Children are endlessly curious; experience often dulls this. Recultivating curiosity means approaching the familiar with fresh eyes, embracing beginner's mind, and finding genuine wonder in the ordinary." },
            { title: 'Lifelong Learning', body: 'The adult brain is far more adaptable than once believed. Every time you learn something new, challenge a belief, or practice a skill, you are physically reshaping your neural architecture. Learning is not just productive — it is one of the deepest acts of care for the self.' },
        ],
        practices: [
            'Choose one long-held belief and spend 20 minutes investigating the strongest counter-argument.',
            'Read one book this month outside your usual area of interest.',
            'Ask "What am I assuming here?" before making an important decision.',
            'Start a question journal — write every genuine question that arises through the day.',
        ],
    },
    {
        id: 'social', num: '04', name: 'Social', icon: '🤝',
        color: '#0369A1', colorLight: 'rgba(3,105,161,0.08)',
        tagline: 'Connected & Belonging',
        shortDesc: 'Your relationships, roles, cultural identity, and sense of belonging.',
        description: "The social self refers to how a person sees themselves in relation to other people. It includes your relationships, social roles, interactions, and how you behave or see yourself when you are with others.",
        example: 'It can be seen in how we communicate, build relationships, cooperate with others, handle conflicts, participate in groups, and fulfill our roles as a family member, friend, student, or member of society.',
        reflectiveQuestion: 'With whom do you feel most fully yourself — and what does that reveal about your truest self?',
        image: IMG.social,
        quote: { text: 'Connection is the energy that exists between people when they feel seen, heard, and valued.', author: 'Brené Brown' },
        lessons: [
            { title: 'The Relational Self', body: 'The self is not formed in isolation — it emerges through relationship. From our earliest attachment bonds with caregivers to our adult friendships and community memberships, who we are is deeply shaped by who we are with. Understanding your relational patterns is essential to understanding yourself.' },
            { title: 'Attachment Styles', body: 'Research on attachment theory reveals that early relational experiences create templates for how we connect as adults. Recognizing your attachment patterns — whether more secure, anxious, or avoidant — is a powerful first step in creating healthier, more intentional relationships.' },
            { title: 'Belonging vs. Fitting In', body: 'Researcher Brené Brown distinguishes between belonging — being accepted as you truly are — and fitting in — changing yourself to be accepted. True belonging requires the courage to be authentic. When we sacrifice authenticity for acceptance, we lose both ourselves and the possibility of genuine connection.' },
            { title: 'Cultural Identity', body: 'Your cultural background, family of origin, community, and social roles are threads woven into your identity. Honoring these influences while consciously choosing which to carry forward requires both gratitude for your roots and courage to grow beyond inherited patterns.' },
        ],
        practices: [
            'Map your relationship ecosystem — who are your three closest connections and how do they shape you?',
            'Practice one genuine act of vulnerability with a trusted person this week.',
            'Reflect on your attachment patterns: Do you tend toward anxious, avoidant, or secure relating?',
            'Identify one community that reflects your deepest values and engage more intentionally.',
        ],
    },
    {
        id: 'spiritual', num: '05', name: 'Spiritual', icon: '✨',
        color: '#059669', colorLight: 'rgba(5,150,105,0.08)',
        tagline: 'Purpose & Meaning',
        shortDesc: 'Your sense of purpose, values, meaning, and connection beyond the everyday.',
        description: 'The spiritual self refers to the part of yourself connected to your beliefs, values, meaning, purpose, and sense of connection to something greater than yourself. It may involve religion, but spirituality can also exist outside organized religion.',
        example: 'It influences our values, decisions, behavior, relationships, priorities, and the way we find meaning, purpose, peace, or direction in life.',
        reflectiveQuestion: 'If your life were perfectly aligned with your deepest values, what would be different from today?',
        image: IMG.spiritual,
        quote: { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
        lessons: [
            { title: 'The Search for Meaning', body: 'Viktor Frankl, who survived the Holocaust, argued that the primary human drive is not pleasure or power but the search for meaning. Meaning cannot be given — it must be found. It can be discovered in work, in love, and in how we respond to unavoidable suffering.' },
            { title: 'Values as a Compass', body: 'Your values are the deep convictions that guide your choices — not what you say you value, but what your consistent actions reveal you value. Clarifying your true values is one of the most powerful acts of self-knowledge. When your life aligns with your values, you experience integrity: the feeling of being whole.' },
            { title: 'Transcendence & Awe', body: 'The spiritual self seeks moments when the boundary between self and world softens — in nature, art, music, meditation, deep love, or service. Research shows that experiences of awe have profound effects on well-being, humility, and generosity. These moments connect us to something larger than our individual concerns.' },
            { title: 'Practice & Ritual', body: 'Spiritual depth is cultivated through practice. Whether meditation, prayer, journaling, time in nature, or acts of service — regular ritual creates space for the spiritual self to deepen. Consistency matters far more than intensity.' },
        ],
        practices: [
            'Write your personal mission: "My life is dedicated to ___."',
            'List your top 5 values and rate how aligned your current life is with each (1–10).',
            'Spend 20 minutes in nature with no phone — notice moments of awe and stillness.',
            'Begin or recommit to one daily practice: meditation, journaling, gratitude, or service.',
        ],
    },
    {
        id: 'digital', num: '06', name: 'Digital', icon: '💻',
        color: '#6D28D9', colorLight: 'rgba(109,40,217,0.08)',
        tagline: 'Identity in the Digital Age',
        shortDesc: 'Your online identity, presence, digital habits, and relationships in digital spaces.',
        description: 'The digital self refers to the way you represent yourself in digital and online spaces. It includes your online identity, profiles, usernames, posts, photos, comments, and interactions.',
        example: 'It appears in how we use social media, communicate online, create or share content, manage our digital identity, protect our privacy, and behave toward other people on the internet.',
        reflectiveQuestion: 'Does your online presence reflect who you truly are — or a curated version of who you wish you were?',
        image: IMG.digital,
        quote: { text: 'The most important thing about technology is how it changes people.', author: 'Jaron Lanier' },
        lessons: [
            { title: 'The Digital Identity', body: 'For the first time in human history, most people maintain two simultaneous selves: a physical self and a digital self. Our online personas — how we present ourselves, what we share, which communities we join — have real consequences for our sense of self, our relationships, and our well-being.' },
            { title: 'Attention as a Resource', body: 'Your attention is finite and precious. Digital platforms are designed by teams of behavioral scientists to capture and hold it. Understanding this — that your engagement is being actively cultivated for profit — is the first step to reclaiming agency over your most valuable cognitive resource.' },
            { title: 'Digital Relationships', body: 'Online connection is real connection, but it is not equivalent to in-person connection. Research shows that passive social media consumption correlates with lower well-being, while active, reciprocal digital engagement can strengthen relationships. The quality of digital connection matters enormously.' },
            { title: 'Intentional Technology', body: 'Digital minimalism is not about rejecting technology — it is about using it with intention. Choosing tools that serve your values, setting clear boundaries around your attention, and protecting time for presence and creativity are all acts of self-care in the digital age.' },
        ],
        practices: [
            'Conduct a digital audit: track your screen time for one week and reflect honestly.',
            'Identify three apps that drain your energy and set one new boundary for each.',
            'Practice one full "digital sunset" — no screens from dinner until bed for three consecutive nights.',
            'Curate your feeds: unfollow accounts that trigger comparison; follow those that genuinely inspire.',
        ],
    },
    {
        id: 'sexual', num: '07', name: 'Sexual', icon: '🌹',
        color: '#BE185D', colorLight: 'rgba(190,24,93,0.08)',
        tagline: 'Identity, Intimacy & Expression',
        shortDesc: 'Your sexual orientation, gender identity, intimacy, and how you express yourself in relationships.',
        description: "The sexual self refers to how a person understands themselves in relation to sexuality, relationships, feelings, values, identity, boundaries, and personal decisions. It is also connected to understanding and respecting one's own body and the boundaries of others.",
        example: 'It involves understanding and respecting our bodies, personal boundaries, relationships, privacy, values, and the boundaries and dignity of other people.',
        reflectiveQuestion: 'How have cultural messages about sexuality shaped your beliefs — and which of those beliefs are truly your own?',
        image: IMG.sexual,
        quote: { text: 'Owning our story and loving ourselves through that process is the bravest thing we will ever do.', author: 'Brené Brown' },
        lessons: [
            { title: 'Sexual Identity', body: 'Sexual identity includes your orientation — who you are attracted to — and your gender identity — your internal sense of being male, female, both, neither, or something else. These are deeply personal aspects of self that exist on a broad spectrum and may evolve over time. Understanding them without judgment is a fundamental act of self-respect.' },
            { title: 'Intimacy & Connection', body: 'Intimacy is far broader than physical contact. It includes emotional vulnerability, deep trust, and the willingness to be truly known by another person. Healthy intimacy requires clear communication, mutual respect, and the courage to express your genuine needs and boundaries — and honor those of others.' },
            { title: 'Values & Boundaries', body: 'Your values around relationships and intimacy form the ethical backbone of your sexual self. These values guide what you seek in partners, how you communicate in relationships, and what limits feel authentic to you. Clarifying your boundaries is not restrictive — it is how you protect what matters most to you.' },
            { title: 'Cultural Influences', body: 'Sexuality is profoundly shaped by culture, family, religion, media, and social norms. Many people carry messages about sexuality that were absorbed uncritically in childhood. Part of developing a healthy sexual self is separating inherited messages from your own authentic understanding — retaining what aligns with your values and releasing what does not.' },
        ],
        practices: [
            'Reflect on the messages about sexuality you received growing up — which do you accept, and which would you revise?',
            'Write about what healthy intimacy means to you — emotionally, not just physically.',
            'Identify one personal boundary in relationships that you have struggled to communicate, and practice naming it clearly.',
            'Explore one trusted resource on healthy relationships or sexual identity — a book, podcast, or counselor — and engage with it openly.',
        ],
    },
];
export const dimensionReflections = {
    physical: [
        {
            progress: { current: 1, total: 3 },
            question: 'How aware are you of your body\'s daily signals — energy, tension, hunger, rest?',
            context: 'Your body communicates constantly. The question is whether you are listening to it.',
            options: [
                { emoji: '🔥', label: 'Very aware', text: 'I check in with my body regularly and respond to what it needs' },
                { emoji: '🌊', label: 'Somewhat', text: 'I notice when signals get loud but often ignore the quiet ones' },
                { emoji: '😶', label: 'Rarely', text: 'I tend to push through without paying attention' },
                { emoji: '❓', label: 'Not sure', text: "I've never thought about listening to my body this way" },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'Which physical habit do you most struggle to maintain?',
            context: 'Physical well-being rests on a few key habits. Honest awareness of gaps is where growth begins.',
            options: [
                { emoji: '😴', label: 'Sleep', text: 'Getting consistent, restful sleep most nights' },
                { emoji: '🏃', label: 'Movement', text: 'Finding time for regular physical activity I enjoy' },
                { emoji: '🥗', label: 'Nourishment', text: 'Eating in a way that gives me steady energy' },
                { emoji: '📵', label: 'Recovery', text: 'Taking real breaks — without screens or stimulation' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'What does your body need more of right now?',
            context: 'If your body could speak one request to you today, what would it most likely ask for?',
            options: [
                { emoji: '🛌', label: 'Rest', text: 'I am running on empty and need to slow down' },
                { emoji: '💪', label: 'Movement', text: 'My body feels stagnant and craves more activity' },
                { emoji: '🌿', label: 'Nourishment', text: "I've been neglecting what I eat and drink" },
                { emoji: '☀️', label: 'Fresh air', text: 'I need more time outside and away from indoor spaces' },
            ],
        },
    ],
    emotional: [
        {
            progress: { current: 1, total: 3 },
            question: 'How often do you name and acknowledge your emotions as they happen?',
            context: 'Naming an emotion is the first act of emotional intelligence. It transforms a feeling into information.',
            options: [
                { emoji: '🌟', label: 'Often', text: 'I check in with my feelings regularly and name them' },
                { emoji: '💛', label: 'Sometimes', text: 'I notice emotions when they become strong or disruptive' },
                { emoji: '😶', label: 'Rarely', text: 'I tend to push feelings aside and carry on' },
                { emoji: '🚪', label: 'Almost never', text: 'Paying attention to emotions feels uncomfortable to me' },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'When a difficult emotion arises, what is your most common response?',
            context: 'How we respond to hard feelings shapes our emotional patterns. There is no wrong answer here.',
            options: [
                { emoji: '💬', label: 'Talk it out', text: 'I talk it through with someone I trust' },
                { emoji: '📓', label: 'Journal', text: 'I write or reflect privately until it becomes clearer' },
                { emoji: '🏃', label: 'Distract', text: 'I distract myself with activity or tasks until it passes' },
                { emoji: '🔒', label: 'Push through', text: 'I push it away and carry on without processing it' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'Which emotional skill do you most want to develop?',
            context: 'Emotional intelligence can be built at any stage of life. Where would growth matter most to you?',
            options: [
                { emoji: '🌡️', label: 'Awareness', text: 'Recognizing and naming my emotions more precisely' },
                { emoji: '🧘', label: 'Regulation', text: 'Responding to strong emotions calmly instead of reactively' },
                { emoji: '❤️', label: 'Empathy', text: 'Feeling and understanding what others are experiencing' },
                { emoji: '💬', label: 'Expression', text: 'Communicating my feelings clearly and honestly' },
            ],
        },
    ],
    intellectual: [
        {
            progress: { current: 1, total: 3 },
            question: 'How would you describe your relationship with learning and curiosity right now?',
            context: 'The intellectual self thrives on genuine curiosity — not forced study, but real wondering.',
            options: [
                { emoji: '🔥', label: 'Actively curious', text: 'I love exploring ideas and regularly seek new knowledge' },
                { emoji: '📚', label: 'Steady', text: 'I learn consistently but don\'t often go deep into new territory' },
                { emoji: '😴', label: 'Dormant', text: "I haven't been stretching my mind much lately" },
                { emoji: '❓', label: 'Uncertain', text: "I'm not sure what genuinely interests me intellectually" },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'When your beliefs or ideas are challenged, how do you typically respond?',
            context: 'Our response to intellectual challenge reveals a great deal about how open our thinking really is.',
            options: [
                { emoji: '🌱', label: 'Open', text: 'I reflect and update my view if the evidence is compelling' },
                { emoji: '🛡️', label: 'Cautious', text: 'I defend my view but try to stay genuinely open' },
                { emoji: '😤', label: 'Uncomfortable', text: 'I tend to feel defensive and struggle to engage calmly' },
                { emoji: '🤔', label: 'Curious but firm', text: 'I get curious about the challenge but rarely shift my position' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'Which intellectual area would you most like to grow in?',
            context: 'The intellectual self grows in many directions — pick the one that feels most alive to you right now.',
            options: [
                { emoji: '🧐', label: 'Critical thinking', text: 'Questioning assumptions and evaluating evidence more carefully' },
                { emoji: '📖', label: 'Knowledge', text: 'Learning more deeply about subjects that genuinely matter to me' },
                { emoji: '💡', label: 'Problem-solving', text: 'Approaching challenges with more creativity and flexibility' },
                { emoji: '🗣️', label: 'Expression', text: 'Communicating ideas and arguments more clearly and persuasively' },
            ],
        },
    ],
    social: [
        {
            progress: { current: 1, total: 3 },
            question: 'How much of your true self do you show in your closest relationships?',
            context: 'Authentic connection requires showing up as you actually are — not a curated or careful version.',
            options: [
                { emoji: '🔓', label: 'Fully', text: 'I am open and authentic — people know who I really am' },
                { emoji: '🌗', label: 'Mostly', text: 'Some walls are still up, but I share a lot' },
                { emoji: '🔒', label: 'Partially', text: 'I share a careful version of myself in most relationships' },
                { emoji: '😶', label: 'Rarely', text: 'I keep most of my inner world private from others' },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'Which aspect of your social self would you most like to strengthen?',
            context: 'The social self develops through intentional practice in relationships and community.',
            options: [
                { emoji: '💬', label: 'Communication', text: 'Expressing my needs and feelings more clearly and directly' },
                { emoji: '🤝', label: 'Trust', text: 'Building deeper trust with people who matter to me' },
                { emoji: '🔲', label: 'Boundaries', text: 'Setting and holding personal limits with greater confidence' },
                { emoji: '🌍', label: 'Community', text: 'Finding and contributing to a community where I truly belong' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'How do your closest relationships influence who you are?',
            context: 'The people we are with shape us — often more than we realize. Honest reflection reveals these patterns.',
            options: [
                { emoji: '🌱', label: 'Growth', text: 'They help me grow and consistently bring out my best self' },
                { emoji: '🪞', label: 'Mirror', text: 'They reflect patterns and blind spots back to me' },
                { emoji: '😤', label: 'Tension', text: 'Some relationships create stress or conflict I haven\'t resolved' },
                { emoji: '🤔', label: 'Still figuring out', text: "I'm still learning how my key relationships shape who I am" },
            ],
        },
    ],
    spiritual: [
        {
            progress: { current: 1, total: 3 },
            question: 'How clear is your sense of personal values and life purpose right now?',
            context: 'The spiritual self is grounded in purpose — knowing what you stand for and why you are here.',
            options: [
                { emoji: '🧭', label: 'Very clear', text: 'I know what I stand for and my choices reflect my values' },
                { emoji: '🌥️', label: 'Somewhat', text: 'I have a general direction but some values feel blurry' },
                { emoji: '🌫️', label: 'Searching', text: "I'm still in the process of discovering what truly matters to me" },
                { emoji: '❓', label: 'Uncertain', text: "I haven't done much deep reflection on purpose and values yet" },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'Which of these gives you the deepest sense of meaning?',
            context: 'Meaning is not found — it is recognized. Notice where your life already feels most significant.',
            options: [
                { emoji: '🌿', label: 'Nature and stillness', text: 'Being outdoors, in quiet, or moments of genuine stillness' },
                { emoji: '❤️', label: 'Serving others', text: 'Contributing to people or causes beyond myself' },
                { emoji: '🎨', label: 'Creating', text: 'Making things, expressing ideas, and bringing something new into being' },
                { emoji: '📖', label: 'Learning and ideas', text: 'Engaging with deep questions, knowledge, and understanding' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'How aligned do you feel between how you live and what you truly value?',
            context: 'Integrity is the feeling of wholeness that comes when your life matches your values.',
            options: [
                { emoji: '✅', label: 'Strongly aligned', text: 'My daily actions and choices genuinely reflect what I care about most' },
                { emoji: '🌊', label: 'Mostly aligned', text: 'There are some gaps between my values and my actions I am aware of' },
                { emoji: '😔', label: 'Partially aligned', text: "There are real disconnects I haven't figured out how to close" },
                { emoji: '❗', label: 'Out of alignment', text: 'I often feel that how I live doesn\'t match what I truly value' },
            ],
        },
    ],
    digital: [
        {
            progress: { current: 1, total: 3 },
            question: 'How intentional are you about how you use digital technology?',
            context: 'Your attention is your most valuable resource. How consciously are you choosing where it goes?',
            options: [
                { emoji: '🎯', label: 'Very intentional', text: 'I set clear limits and make deliberate choices about my screen use' },
                { emoji: '🌊', label: 'Somewhat', text: 'I try to be mindful but often drift into habitual scrolling' },
                { emoji: '😶', label: 'Not very', text: 'I use technology without much conscious thought or structure' },
                { emoji: '📵', label: 'Honestly unsure', text: "I don't really know where a lot of my digital time goes" },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'How honestly does your online presence reflect who you actually are?',
            context: 'The gap between your digital self and your real self reveals something important about identity.',
            options: [
                { emoji: '🔓', label: 'Authentically', text: 'My online presence is a genuine extension of who I am' },
                { emoji: '🎭', label: 'Somewhat curated', text: 'I shape my online image but it still reflects real values' },
                { emoji: '🪞', label: 'A performance', text: 'My digital self is quite different from my real self' },
                { emoji: '❓', label: 'Never considered it', text: "I haven't thought much about this distinction before" },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'Which digital habit would you most like to change?',
            context: 'Digital well-being is about intentionality — choosing how technology serves you, not consumes you.',
            options: [
                { emoji: '⏱️', label: 'Less scrolling', text: 'Reducing mindless, passive browsing and content consumption' },
                { emoji: '📵', label: 'Screen-free time', text: 'Creating more intentional breaks from devices each day' },
                { emoji: '🔒', label: 'Privacy habits', text: 'Being more careful about what I share and how I am tracked online' },
                { emoji: '🌐', label: 'Conscious posting', text: 'Being more thoughtful and intentional about what I put online' },
            ],
        },
    ],
    sexual: [
        {
            progress: { current: 1, total: 3 },
            question: 'How comfortable are you reflecting on your values around intimacy and close relationships?',
            context: 'The sexual self is one of the most personal dimensions. Honest reflection, at your own pace, is valuable.',
            options: [
                { emoji: '🌸', label: 'Comfortable', text: 'I have reflected on this before and feel ready to engage honestly' },
                { emoji: '🌿', label: 'Somewhat', text: 'It can feel unfamiliar, but I am open to exploring it thoughtfully' },
                { emoji: '😶', label: 'A little cautious', text: 'This area feels sensitive to me, but I am willing to try' },
                { emoji: '🔒', label: 'Guarded', text: 'I tend to avoid reflection in this area — it feels private or uncomfortable' },
            ],
        },
        {
            progress: { current: 2, total: 3 },
            question: 'Which of these feels most important to you in close, intimate relationships?',
            context: 'Your values in relationships form the foundation of your sexual self and how you connect with others.',
            options: [
                { emoji: '🤝', label: 'Mutual respect', text: 'Clear communication and being genuinely heard and valued' },
                { emoji: '🛡️', label: 'Safety and consent', text: 'Feeling safe and having my personal boundaries honored at all times' },
                { emoji: '❤️', label: 'Emotional intimacy', text: 'Deep vulnerability, trust, and being truly known by another person' },
                { emoji: '🔑', label: 'Authentic identity', text: 'Honesty about who I am and what I genuinely need in relationships' },
            ],
        },
        {
            progress: { current: 3, total: 3 },
            question: 'What would help you feel more grounded and secure in your close relationships?',
            context: 'Building a healthy sexual and relational self is an ongoing process of learning, reflection, and growth.',
            options: [
                { emoji: '💬', label: 'Better communication', text: 'Learning to express my needs and personal limits more clearly' },
                { emoji: '📚', label: 'More understanding', text: 'Learning more about what healthy, respectful relationships look like' },
                { emoji: '🌸', label: 'Self-acceptance', text: 'Feeling less judgment — from myself or others — about my identity' },
                { emoji: '🤲', label: 'Honest conversations', text: 'Having open discussions about consent, respect, and boundaries' },
            ],
        },
    ],
};
// ─── Quiz Questions ───────────────────────────────────────────────────────────
export const quizQuestions = [
    {
        id: 1,
        question: 'When you feel overwhelmed, which dimension do you most naturally turn to?',
        options: [
            { label: 'Movement or physical activity', dim: 'physical' },
            { label: 'Talking through feelings with someone', dim: 'emotional' },
            { label: 'Reading, journaling, or problem-solving', dim: 'intellectual' },
            { label: 'Spending time with loved ones', dim: 'social' },
            { label: 'Quiet reflection or meditation', dim: 'spiritual' },
            { label: 'Listening to music or browsing online', dim: 'digital' },
            { label: 'Reflecting on my relationships and intimacy', dim: 'sexual' },
        ],
    },
    {
        id: 2,
        question: 'Which area of your life feels most alive and engaged right now?',
        options: [
            { label: 'My health and physical vitality', dim: 'physical' },
            { label: 'My emotional intelligence and empathy', dim: 'emotional' },
            { label: 'My curiosity and learning', dim: 'intellectual' },
            { label: 'My relationships and community', dim: 'social' },
            { label: 'My sense of purpose and values', dim: 'spiritual' },
            { label: 'My digital presence and creativity', dim: 'digital' },
            { label: 'My sense of intimacy and identity in relationships', dim: 'sexual' },
        ],
    },
    {
        id: 3,
        question: 'Which dimension most needs your attention right now?',
        options: [
            { label: 'Taking better care of my body', dim: 'physical' },
            { label: 'Processing unresolved emotions', dim: 'emotional' },
            { label: 'Expanding my thinking and knowledge', dim: 'intellectual' },
            { label: 'Deepening my relationships', dim: 'social' },
            { label: 'Clarifying my values and purpose', dim: 'spiritual' },
            { label: 'Creating healthier digital habits', dim: 'digital' },
            { label: 'Understanding my identity and approach to intimacy', dim: 'sexual' },
        ],
    },
];
